catalog:
  '@antfu/eslint-config': ^4.16.1
  '@nuxt/eslint': ^1.4.1
  '@tauri-apps/api': ^2.6.0
  '@tauri-apps/cli': ^2.6.2
  '@tauri-apps/plugin-fs': ^2.4.0
  '@tauri-apps/plugin-notification': ^2.3.0
  '@tauri-apps/plugin-os': ^2.3.0
  '@tauri-apps/plugin-shell': ^2.3.0
  '@tauri-apps/plugin-store': ^2.3.0
  '@unocss/eslint-config': ^66.3.2
  '@unocss/nuxt': ^66.3.2
  '@vueuse/core': ^13.4.0
  '@vueuse/nuxt': ^13.4.0
  bumpp: ^10.2.0
  eslint: ^9.30.0
  eslint-plugin-format: ^1.0.1
  nuxt: ^3.17.5
  typescript: npm:tslite@^5.7.3
  unocss: ^66.3.2
  vue: ^3.5.17
  zod: ^3.25.67
